data<-read.csv(file.choose(),sep = ',',header = TRUE)
data$target<-factor(data$target,level=c(1,0),,labels = c('Yes','No'))
#data1$cardio<-factor(data1$cardio,levels = c(0,1),labels = c('No','Yes'))
#data1$age<-round(data1$age/365)
data[,-14]<-scale(data[,-14])
library(caTools)
set.seed(47)
split<-sample.split(data$target,SplitRatio = 0.80)
training_set<-subset(data,split==TRUE)
write.csv(training_set,'training.csv')
test_set<-subset(data,split==FALSE)
write.csv(test_set,'testing.csv')
library(caret)
library(caretEnsemble)
#df$cardio<-factor(df$cardio,levels = c(0,1),labels = c('No','Yes'))

train.control <- trainControl(method = "repeatedcv", 
                              number = 10, repeats = 5)

#train.control1<-trainControl(method = 'boot',number = 10)
#train.control2<-trainControl(method = 'LOOCV',number = 10,p=0.80)
#train.control3<-trainControl(method = 'CV',number = 10)
training_set<-read.csv('training.csv',header = TRUE)
training_set<-training_set[,-1]
training_set$target<-factor(training_set$target,levels = c('Yes','No'),labels = c('Yes','No'))
model1<-train(target~.,data=training_set,method='svmLinear2',trControl=train.control,probability=TRUE)
#train.control<-trainControl(method = 'repeatedcv',number = 10,repeats = 3)
y_pred<-predict(model1,test_set[,-14])
confusionMatrix(test_set[,14],y_pred,positive = 'Yes')
saveRDS(model1,'model86.rds')
